//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loundry
    {
        public int ID_Loundry { get; set; }
        public Nullable<System.DateTime> Tgl_Masuk { get; set; }
        public Nullable<System.DateTime> Tgl_Keluar { get; set; }
        public Nullable<int> Berat { get; set; }
        public Nullable<int> ID_Pelanggan { get; set; }
        public Nullable<int> ID_Jenis_Pakaian { get; set; }
        public Nullable<int> ID_Pewangi { get; set; }
        public Nullable<int> ID_Paket { get; set; }
    
        public virtual Jenis_Pakaian Jenis_Pakaian { get; set; }
        public virtual Paket Paket { get; set; }
        public virtual Pelanggan Pelanggan { get; set; }
        public virtual Pewangi Pewangi { get; set; }
    }
}
