//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelanggan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelanggan()
        {
            this.Loundries = new HashSet<Loundry>();
        }
    
        public int ID_Pelanggan { get; set; }
        public string nama_pelanggan { get; set; }
        public string alamat { get; set; }
        public string no_hp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loundry> Loundries { get; set; }
    }
}
